<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>DL2 / Slim Controller 1.x</title>
    <style>
      html, body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif
      }

      body {
        color: #aaa;
        font-size: 1.2em;
        margin: 5%;
      }

      h1 {
        color: #719e40;
        font-size: 100px;
        font-weight: 300;
        letter-spacing: -3px;
        margin-bottom: 0;
      }

      sup {
        color: #888;
      }
    </style>
  </head>
  <body>
    <h1>DL2 / Slim Controller <sup>1.0</sup></h1>
    <h2>Action Controllers made easy!</h2>
  </body>
</html>
